### PR TITLE
Total Revamp

### PR DESCRIPTION
**Pull request by danrschlosser**
Hey team!

I thought it would be nice to revive this site from the dead, so I gave it a facelift!  I also added a "rankings" page, which shows which schools have what datasets open.  If we push this, we could get a really solid view of how we're doing on open data things!

Check out the screenshots below:

## Homepage 

index

## Join page (members)
join

## Rankings

rankings

## The guidebook
*Screenshot is weird, but that's a scrollspying table of contents*
guidebook

### CODE REVIEW

**Comment by KartikTalwar** [comment]
Wow this is so awesome! @danrschlosser

**Comment by KartikTalwar** [comment]
I can do a thorough review if you'd like but I think we make this live! My only comment would be to make the heights of the box the same for all universities in Join page (members)

**Comment by danrschlosser** [comment]
Done, as well as:
- made google forms for all the signups and pointed things there
- made a google group that ppl can email: campusdata@googlegroups.com
- changed "join" to "members"

**Comment by AlexeyMK** [comment]
Very cool!

**Comment by yefim** [comment]
Woah, awesome :+1:

**Pull request merged**
